<?php

// Create our custom group and fields
return array(
  0 => array(		
    'entity' => 'ContactType',
    'name' => 'foundationfields_foundation',
    'update' => 'never',
    'params' => array(
      'version' => 3,
      'name' => 'foundationfields_foundation',
      'label' => 'Foundation',
      'parent_id' => '3',
      'is_active' => '1',
    ),
  ),
  1 => array(
    'entity' => 'CustomGroup',
    'name' => 'foundationfields_foundation_info',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'is_active' => 1,
      'name' => 'foundationfields_foundation_info',
      'title' => 'Foundation Info',
      'extends' => 'Organization',
      'extends_entity_column_value' => 'foundationfields_foundation',
      'style' => 'inline',
      'collapse_display' => '0',
      'is_active' => '1',
      'is_multiple' => '0',
      'collapse_adv_display' => '0',
      'is_reserved' => '0',
      'is_public' => '1',
      'api.custom_field.create' => array(
         array(
           'custom_group_id' => '$value.id',
           'label' => 'Average Amount',
           'name' => 'foundationfields_average_amount',
           'data_type' => 'Money',
           'html_type' => 'Text',
           'is_required' => '0',
           'is_searchable' => '1',
           'is_search_range' => '1',
           'weight' => '10',
           'is_active' => '1',
           'is_view' => '0',
           'text_length' => '255',
           'note_columns' => '60',
           'note_rows' => '4',
           'in_selector' => '0'
         ),
         array(
           'custom_group_id' => '$value.id',
           'label' => 'Funding Areas',
           'name' => 'foundationfields_funding_area',
           'data_type' => 'String',
           'html_type' => 'CheckBox',
           'is_required' => '0',
           'is_searchable' => '1',
           'is_search_range' => '0',
           'weight' => '20',
           'is_active' => '1',
           'is_view' => '0',
           'options_per_line' => '2',
           'text_length' => '255',
           'note_columns' => '60',
           'note_rows' => '4',
           'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Requirements Notes',
          'name' => 'foundationfields_requirement_notes',
          'data_type' => 'Memo',
          'html_type' => 'RichTextEditor',
          'is_required' => '0',
          'is_searchable' => '0',
          'is_search_range' => '0',
          'weight' => '30',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
      ),
    ),
  ),
  2 => array(
    'entity' => 'OptionValue',
    'name' => 'foundationfields_letter_of_inquiry',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'option_group_id' => 'activity_type',
      'label' => 'Letter of Inquiry',
      'name' => 'foundationfields_letter_of_inquiry',
      'filter' => '0',
      'is_default' => '0',
      'is_optgroup' => '0',
      'is_reserved' => '0',
      'is_active' => '1',
    ),
  ),
  3 => array(
    'entity' => 'OptionValue',
    'name' => 'foundationfields_report',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'option_group_id' => 'activity_type',
      'label' => 'Report',
      'name' => 'foundationfields_report',
      'filter' => '0',
      'is_default' => '0',
      'is_optgroup' => '0',
      'is_reserved' => '0',
      'is_active' => '1',
    ),
  ),
  4 => array(
    'entity' => 'OptionValue',
    'name' => 'foundationfields_proposal',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'option_group_id' => 'activity_type',
      'label' => 'Proposal',
      'name' => 'foundationfields_proposal',
      'filter' => '0',
      'is_default' => '0',
      'is_optgroup' => '0',
      'is_reserved' => '0',
      'is_active' => '1',
    ),
  ),
  5 => array(
    'entity' => 'CustomGroup',
    'name' => 'foundationfields_proposal_info',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'is_active' => 1,
      'name' => 'foundationfields_proposal_info',
      'title' => 'Proposal Info',
      'extends' => 'Activity',
      'extends_entity_column_value' => array(),
      'style' => 'inline',
      'collapse_display' => '0',
      'is_active' => '1',
      'is_multiple' => '0',
      'collapse_adv_display' => '0',
      'is_reserved' => '0',
      'is_public' => '1',
      'api.custom_field.create' => array(
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Ask Amount',
          'name' => 'foundationfields_ask_amount',
          'data_type' => 'Money',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '1',
          'weight' => '10',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Amount to be Received',
          'name' => 'foundationfields_amount_to_be_received',
          'data_type' => 'Money',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '1',
          'weight' => '20',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Date to be Received',
          'name' => 'foundationfields_date_to_be_received',
          'data_type' => 'Date',
          'html_type' => 'Select Date',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '1',
          'weight' => '30',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'start_date_years' => '30',
          'end_date_years' => '5',
          'date_format' => 'mm/dd/yy',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Multiyear Grant',
          'name' => 'foundationfields_multiyear_grant',
          'data_type' => 'Boolean',
          'html_type' => 'Radio',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '40',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Years',
          'name' => 'foundationfields_years',
          'data_type' => 'Float',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '1',
          'weight' => '50',
          'help_post' => 'Enter number of years for a multi-year grant',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Proposal Status',
          'name' => 'foundationfields_proposal_status',
          'data_type' => 'String',
          'html_type' => 'Select',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '60',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
      ),
    ),
  ),
  6 => array(
    'entity' => 'OptionGroup',
    'name' => 'foundationfields_proposal_status_values',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'name' => 'foundationfields_proposal_status_values',
      'title' => 'Proposal Status Values',
      'is_reserved' => '1',
      'is_active' => '1',
      'is_locked' => '0',
      'api.option_value.create' => array(
        array(
          'option_group_id' => '$value.id',
          'label' => 'Accepted',
          'name' => 'foundationfields_accepted',
          'value' => '1',
          'is_default' => '0',
          'weight' => '10',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Pending',
          'name' => 'foundationfields_pending',
          'value' => '2',
          'is_default' => '0',
          'weight' => '20',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Rejected',
          'name' => 'foundationfields_rejected',
          'value' => '3',
          'is_default' => '0',
          'weight' => '30',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Resubmitted',
          'name' => 'foundationfields_resubmitted',
          'value' => '4',
          'is_default' => '0',
          'weight' => '40',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
      ),
    ),
  ),
  7 => array(
    'entity' => 'OptionGroup',
    'name' => 'foundationfields_funding_area_values',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'name' => 'foundationfields_funding_area_values',
      'title' => 'Funding areas',
      'is_reserved' => '1',
      'is_active' => '1',
      'is_locked' => '0',
      'api.option_value.create' => array(
        array(
          'option_group_id' => '$value.id',
          'label' => 'Immigrant Rights',
          'name' => 'foundationfields_immigrant_rights',
          'value' => '1',
          'is_default' => '0',
          'weight' => '10',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Economic Justice',
          'name' => 'foundationfields_economic_justice',
          'value' => '2',
          'is_default' => '0',
          'weight' => '20',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Workers Rights',
          'name' => 'foundationfields_workers_rights',
          'value' => '3',
          'is_default' => '0',
          'weight' => '30',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Environmental Justice',
          'name' => 'foundationfields_environmental_justice',
          'value' => '4',
          'is_default' => '0',
          'weight' => '40',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
      ),
    ),
  ),
);
